### ISSUE TITLE
nrf SDK can be used for dongle 52840 or not?

### ISSUE THREAD

**Issue by ashwinr3421** [NordicPlayground/nRF5x-custom-ble-service-tutorial#6]
There is a requirement for me to create a custom service and test it via nrf52840 dongle.  Now I got a doubt, to use nrf SDK we need nrf52840 development board, or nrf52840 dongle is enough?

**Comment by bjornspock** [comment]
@ashwinr3421: The nRF5 SDK supports the nRF52840 Dongle (PCA10059), see [Supported Boards](https://infocenter.nordicsemi.com/topic/sdk_nrf5_v17.1.0/sdk_for_custom_boards.html?cp=9_1_1_5_0#supported_board) in the nRF5 SDK documentation.

**Comment by ashwinr3421** [comment]
Thank you @bjornspock.
